DROP TABLE IF EXISTS forms ;
CREATE TABLE forms(
  id INTEGER PRIMARY KEY,
  name STRING NOT NULL,
  contact STRING NOT NULL,
  message STRING NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)