DROP TABLE IF EXISTS users ;
CREATE TABLE users(
  id INTEGER PRIMARY KEY,
  public_id STRING NULL,
  name STRING NOT NULL,
  username STRING NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)

-- CREAR TABLAS NOTAS Y GRUPOS DE NOTAS