DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS notegroup;

CREATE TABLE notes(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content TEXT NOT NULL,
  group_id INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (group_id) REFERENCES notegroup(id) ON DELETE CASCADE
);

CREATE TABLE notegroup(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);